### ISSUE TITLE
Is this project really Ultra Modern Perl 5?

### ISSUE THREAD

**Issue by yuki-kimoto** [MoeOrganization/moe#76]
Is this project really Ultra Modern Perl 5?

It looks like sister language like perl 6.
I don't deny your project, but some people think moe is perl5 reimplementation + α.

If you don't use perl5 syntax, i think this project isn't Ultra Modern Perl 5 because this don't has backkword compatible to perl5 at all.

For example, $obj.length is not perl5, sub foo is bar { ... } is not perl5.

I don't deny your project, 
but if this project is called Ultra Modern Perl 5, this caption maybe give a false impression to many people.

**Comment by ghost** [comment]
On Apr 8, 2013 1:16 PM, "Yuki Kimoto" notifications@github.com wrote:

> Is this project really Ultra Modern Perl 5?
> 
> Yes, in the sense that it is an attempt to see how perl 5 would have
> evolved if we were to remove old baggage and introduce new things.
> 
> It looks like sister language like perl 6.
> I don't deny your project, but some people think moe is perl5
> reimplementation + α.
> 
> Doesn't matter. See below.
> If you don't use perl5 syntax, i think this project isn't Ultra Modern
> Perl 5 because this don't has backkword compatible to perl5 at all.
> 
> See above. Change means we throw out the old and bring in the new. Moe is
> trying to do that, it doesn't have to be fully backward compatible with
> perl 5. That said, it retains some of perl 5 features that are useful.
> For example, $obj.length is not perl5, sub foo is bar { ... } is not
> perl5.
> 
> I don't deny your project,
> but if this project is called Ultra Modern Perl 5, this caption maybe
> give a false impression to many people.
> 
> First, this is not a native reimplementation of perl 5, but an
> implementation that targets the jvm. There's nothing wrong if it looks to
> perl 6 for inspiration/ideas.

With all that said, this project, like every other project has its purpose.
I assume you have looked at Stevan's talk? Welcome to Moe. :)

**Comment by yuki-kimoto** [comment]
I don't seek  fully backward compatible. but if basic syntax like $self->title don't work, it is not perl, it is one language similar to perl. If all current perl source code don't work, it is not perl.

**Comment by xsawyerx** [comment]
Can you really reduce the entire Perl language to specific syntax quirks like `->`? What about the fact that the namespace `D'oh` actually works? Does fixing it means it's no longer Perl? Does removing UNIX-specific formatting makes it not Perl anymore? What about having a core MOP? Would it still be Perl?

Perl as a language has to be defined in more than its pure syntax, otherwise there's no point in any of it. It's about approach, it's about how dynamic it is, it's about how powerful it is. Moe takes all these ideas and fixes bits of the syntax that we either find difficult, confusing or nonsensical. Nothing wrong with that. In fact, that is what would leverage Moe as a successful reimplementation.

I hope this is good enough to answer the question presented in the ticket.

**Comment by jjl** [comment]
On 8 Apr 2013, at 12:54, Yuki Kimoto notifications@github.com wrote:

> I don't seek fully backward compatible. but if basic syntax like $self->title don't work, it is not perl, it is one language similar to perl. If all current perl source code don't work, it is not perl.
> 
> —
> Reply to this email directly or view it on GitHub.

qq(It is simplest perhaps to start by saying what this project is not, it is not an attempt to create a production version of Perl 5 on the JVM.
Instead, this project is an /experiment/ to see what a cleaned up and slimmed down Perl 5 might look like. The key word here is "experiment", because no one knows exactly what that will look like, and I want to try and find out.)

(taken from the README.md)

Is there something unclear about that?

James

**Comment by stevan** [comment]
@yuki-kimoto 

I do not disagree that Moe is morphing into a Perl 6 "Lite", however I would argue that any "ultra modern" Perl 5 will almost certainly steal a lot from Perl 6 and end up looking very similar to it. In that sense I don't think that "Ultra Modern Perl 5" is misleading.

As for the discussion about backwards compatibility, I have done a lot of thinking about this (a LOT of thinking). The whole reason for trying to maintain backwards compatibility with Perl 5 is to retain as much of CPAN as possible, and I have come to the (somewhat sad) conclusion that that is a completely impossible goal. 

Unless we support the features like AUTOLOAD, tie/untie and reimplement XS (all three of which were high on the list of things people really want to see go away), then we will not be able to support 90% of the useful modules on CPAN. 

Additionally, this project was largely born from my frustration with getting the p5-mop into Perl 5, so obviously I will be making the MOP a centerpiece of this implementation. If you were to have a real MOP and a proper object system, then why would you want to also support the (comparatively) clunky blessed-reference/package object system? And if I don't maintain backwards compatibility with old style Perl 5 OO, then any remaining CPAN modules and a huge percentage of DarkPAN modules simply can not be supported.

But I ultimately do not see this as a negative thing. While CPAN is a wonderful resource with lots of very useful modules, it is beginning to show it's age. If you take a look at some of the key modules on the CPAN -- DBI and LWP for example -- you will find their internals littered with old idioms and outdated best practices. This is not a slight on their authors so much as just a comment on the times in which these modules were written (DBI was first released in September of 1994 and LWP in May of 1995). Both of these modules are due for a re-write, as are a number of other key modules on CPAN that suffer from the weight of backwards compatibility. 

It is my hope that by making a Perl-like language (neither 5 nor 6 specifically, because I would argue that Moe is somewhere in between), porting old Perl code will be easier then say, porting to Python or Ruby or Scala or $some_other_language. If at the core Moe is just a dialect of Perl, then it will be a much simpler transformation then completely transposing to another language entirely. And because we are moving closer to Perl 6, I hope that Moe would also serve as a bridge between the two languages as well.

And as @jjl pointed out, this is a research project and therefore a place for experimentation, nothing that happens with Moe should be thought of as anything other then that.

Thanks,

Stevan

**Comment by yuki-kimoto** [comment]
I'm afraid that many people don't use moe because the people who want clean syntax will choice ruby and python. 
many of them hate sigil $.

> Unless we support the features like AUTOLOAD, tie/untie and reimplement XS (all three of which were high on the list of things people really want to see go away), then we will not be able to support 90% of the useful modules on CPAN.

i don't seek AUTOLOAD, tie/untie, reimplement XS, and format, attribute,  but i want same basic syntax as perl5 for perl5 user to use moe easily. For example, people can create GUI application on smartphone using perl syntax.

**Comment by stevan** [comment]
@yuki-kimoto is your issue only with the switch from `->` to `.` or do you have more issues with Moe then that?

In my opinion, the `sub foo is bar {}` syntax is not much different then `sub foo :bar() {}` and much nicer.

**Comment by yuki-kimoto** [comment]
I list **my** opinions. 

**Good thing:**
1. true and false syntax
2. Java VM based thread because ithread is broken.
3. Subroutine signature

**Bad thing:**
1. method call: I like -> than . because perl5 user
   is familiar with it. Typing numbar is 2, but if this is changed,
   most of all pure perl soruce code don't work.
   moe will be blamed same as perl6's way.
2. Here document: I like <<"EOS" than """ """ because perl5 user
   is familiar with it.
3. subroutine attribute: i think this is no needed
   because other language don't have it usually.
   this make syntax more difficult.
4. Array access: I like $foo[$i] than @foo[$i] because perl5 user
   is familiar with it. if this is changed,
   most of all pure perl soruce code don't work.
5. Hash accesss: same as array access.
6. Array asignment: I like my @bar = () than my @bar = [].
   because perl5 user is familiar with it. if this is changed,
   most of all pure perl soruce code don't work.
7. Hash asignment: Same as array asignment.

**More argument needed:**
1. Class syntax and meta object protocol.

**Other**

I see clean and fast and flexible perl5 minimum implementation at first before many usuful features is added.

**Comment by jjl** [comment]
> In my opinion, the sub foo is bar {} syntax is not much different then sub foo :bar() {} and much nicer.
> 
> Without question it's nicer. But actually _I_ don't like it. Not because it isn't nice, because in perl, attributes stick out as being an unusual thing mentally from the syntax.

Actually, I think moe gets this wrong in a few places. That and the property of wrong code looking immediately wrong, which I was discussing with a friend on the tube last night. The "cleaner" you make things, often the more difficult they become to debug because things don't leap out at you. One of the hardest things I ever had to debug was written in python. It certainly wasn't because I couldn't read the code...

**Comment by stevan** [comment]
@jjl - it is my hope that because Moe has an AST and has been built specifically for tooling in mind, that you won't need to just look at your code to see what is wrong, but that your tools will help you figure out what it wrong. 

As for the difference between `is bar` and `:bar` I see that as just a minor syntactical thing, whereas the features and extensibility offered by traits (NOTE: not yet implemented in Moe, for the time it is a bit of a hack) is much better then the clunky and (mostly) broken API for attributes. Is your issue with the syntax or with the underlying functionality?

**Comment by stevan** [comment]
@yuki-kimoto 

Let me first say that it is impossible to move forward if you must drag all the mistakes of the past with you, this is why the current perl implementation is in the state that it is. 

**re: -> vs .**

Let me be clear, pure Perl source code will **never** work with Moe without some level of (hopefully automated) syntax transformation. Even if we kept `->` this would be true, and honestly transforming `->` to `.` is pretty trivial as syntax transformations go. 

**re: Here documents**

You are confusing the Scala with Moe, the `""" """` syntax is Scala's multiline string, there is no support planned for it in Moe. In all likeliness Moe will support here documents and quote blocks (`q{}`, `qq{}`, etc.).

**re: subroutine attributes**

I disagree, just about _every_ other language I know has them to some degree or another, I think what is confusing you is the placement. Take the familiar Java/C++ style `public` modifier:

```
public sub foo ($x) { ... }
```

this would look like this in Moe:

```
sub foo ($x) is public { ... }
```

but underneath, they are exactly the same thing. 

**re: array and hash access and assignment**

The switching of the sigils depending upon context (element access vs. container access) is something that is actually extremely confusing to new Perl users. This is made even more confusing by the separation of references and non-references. The goal is Moe is for everything to be an object (same as Perl 6, Ruby, Python, Javascript, Java, C#, etc.) which means there is no difference between an array and an array reference, which means that the syntactic warts of the past (and confusing sigils) can be fixed.

**re: discussion about class syntax and MOP**

I am following the Perl 6 class syntax, basically because Larry Wall is a far better language designer then I will ever be. If we want a perlish syntax for classes then what better source then the mind of Larry :)

Regarding the MOP, the user accessible portions of it have not been built yet, but they will likely follow the basic design of Moose as that has proven successful over the last 7 years.

> I see clean and fast and flexible perl5 minimum implementation at first before many usuful features is added.

But what is the language for that "minimum implementation"? **Perl** the language is very closely tied to `perl` the compiler/runtime, much of the syntax -- good and bad -- exists because of some (mis)feature that is present in the runtime. A lot of the syntactical oddities that we all know and love exist not because of any focused design effort, but because of `perl`'s fervent commitment to backwards compatibility (for better or for worse). 

Keep in mind that my goal is not just to improve the language with things like subroutine signatures and class syntax or to open up the possibility of having sane threads. I also want to help make the syntax more consistent and the runtime less insanely complex so that we can have the benefits that so many other languages get from modern development tools. 

@yuki-kimoto, I understand your concerns and I very much appreciate this discussion, but I think moving forward _requires_ change and unfortunately, change is never easy.

**Comment by jjl** [comment]
> As for the difference between is bar and :bar I see that as just a minor syntactical thing, whereas the features and extensibility offered by traits (NOTE: not yet implemented in Moe, for the time it is a bit of a hack) is much better then the clunky and (mostly) broken API for attributes. Is your issue with the syntax or with the underlying functionality.
> 
> @stevan, I'm talking purely about syntax here. Perl has this odd habit of looking wrong when it's wrong, which turns out to be quite a boon when trying to track down a bug in your program. Whilst what you've got here looks cleaner, it doesn't leap out suddenly as being an attribute. I'm sure my brain would get used to this one readily enough, but there are other aspects.

On this topic, I think invariant sigils do a similar kind of thing. By marking the beginning with a specifier of whether i'm after one or multiple items, my brain context switches to check the typing automatically. I also appreciate that's something that was argued about a lot when they were deciding it for perl 6. Some people love them, some people hate them. Some people hate sigils altogether. I'm mainly focused on wrong code looking wrong.

James

**Comment by ribasushi** [comment]
Um... reading here and the twitter-fest that ensued - I have a real serious question (really not attempting to troll).

If you are planning to depart so far away from Perl5 (the language) and gravitate so close to Perl6 (the language) - what is the point of Moe in the first place? Wouldn't it be infinitely more productive to redirect effort towards Rakudo or Niecza? 

It basically seems like Moe aims (without claiming so anywhere) to be another entry on this list: http://perl6.org/compilers/

**Comment by stevan** [comment]
@jjl, I can appreciate what you mean about this, but I believe that if we have a clean AST that can be traversed and analyzed from a number of different directions any bug-trackability you might loose from having a cleaner syntax will be replaced by having tools that can detect it for you. Think of it as Perl Critic, but with better access to the language then what PPI can provide.

**Comment by stevan** [comment]
@ribasushi Perl 6 is a _HUGE_ language, Moe does not aim to come anywhere close to its size and complexity. 

I am aiming for somewhere in the middle between Perl 5 and Perl 6, which means it won't look exactly like the Perl 5 you are used too, but it also won't look exactly like the Perl 6 we've all been waiting for. 

Keep in mind too that this is still a work in progress and we have a long way to go still.

**Comment by chenryn** [comment]
Means Moe is a "cleaner" language with "some" Perl6 features??

2013/4/9 Stevan Little notifications@github.com

**Comment by stevan** [comment]
@chenryn yes that is a good characterization, because I am not taking all of the Perl 6 feature set.

**Comment by yuki-kimoto** [comment]
I think prograｍming language implementation is very very difficult.
Normal ability programmer can't implement prograｍming language itself.
You are very high ability to create program.
You can create prograｍming language from zero.

Some people (which contain me) want to see perl5 implementation on Java VM.
Implementation don't yet exists.
If you don't like perl5 syntax, you can change it later.
People which like perl5 syntax can fork moe to create perl5 re-implementation.

The person which can implement programｍing language from zero is very rare.
Can you remain the way to re-implement perl5 on Java VM for a while?

> Let me first say that it is impossible to move forward if you must drag all the mistakes of the past with you, this is why the current perl implementation is in the state that it is. re: -> vs .Let me be clear, pure Perl source code will never work with Moe without some level of (hopefully automated) syntax transformation. Even if we kept -> this would be true, and honestly transforming -> to . is pretty trivial as syntax transformations go.

I think . is good and clean, but -> is not bad.
I think changing perl basic syntax is very bad
because it is no longer perl.

> re:subroutine attributes. I disagree, just about every other language I know has them to some degree or another, I think what is confusing you is the placement. Take the familiar Java/C++ style public modifier:

If qualifier is needed, I like the following syntax same as perl5.
Subroutine attribute is bad because any string is received, not syntax.

```
sub foo : public { ... }
```

> re: array and hash access and assignment. The switching of the sigils depending upon context (element access vs. container access) is something that is actually extremely confusing to new Perl users. This is made even more confusing by the separation of references and non-references. The goal is Moe is for everything to be an object (same as Perl 6, Ruby, Python, Javascript, Java, C#, etc.) which means there is no difference between an array and an array reference, which means that the syntactic warts of the past (and confusing sigils) can be fixed.

I think moe target is perl5 user, not newbie. perl5 user think $ is one thing, @ is muｌtiple things.
Reference is a little difficult, but it is basic syntax in perl5.
If this is changed, it is no longer perl.

> re: discussion about class syntax and MOP. I am following the Perl 6 class syntax, basically because Larry Wall is a far better language designer then I will ever be. If we want a perlish syntax for classes then what better source then the mind of Larry :) Regarding the MOP, the user accessible portions of it have not been built yet, but they will likely follow the basic design of Moose as that has proven successful over the last 7 years.

I like single inheritance and delegation.
For example, Mojolicious has very clean code.
so I don't yet understand why meta object protocol is needed.

> I see clean and fast and flexible perl5 minimum implementation at first before many usuful features is added.
> But what is the language for that "minimum implementation"? Perl the language is very closely tied to perl the compiler/runtime, much of the syntax -- good and bad -- exists because of some (mis)feature that is present in the runtime. A lot of the syntactical oddities that we all know and love exist not because of any focused design effort, but because of perl's fervent commitment to backwards compatibility (for better or for worse).

For example, perl ithread is broken. People see python and ruby green thread good.
perl5 can't get new thread system. This is frustration.
Creating true and false syntax break perl5 core. This is frustration.

->, reference, :, standard function is not frustration.
This is perl basic syntax which all perl users are familiar with.
If these is changed, user must learn two different syntax.
It is very very bad.

**Comment by stevan** [comment]
@yuki-kimoto 

To be honest I am just not interested in replicating the existing Perl 5 language (warts and all) on the JVM. I am more interested in moving things forward in the way that I think it should go (which is moving towards Perl 6 and breaking backwards compatibility). 

I appreciate your passion on this subject, but I think if you are really keen on replicating Perl 5 on the JVM you should fork Moe and give it a try. I did my best to structure Moe in a sensible and clean way so that it would be easy to hack on, and therefore it should be easy to fork and change as well.

Thanks,

Stevan

**Comment by jjl** [comment]
> I appreciate your passion on this subject, but I think if you are really keen on replicating Perl 5 on the JVM you should fork Moe and give it a try.

Or look at p5vm, an old project where kitty and I tried to make perl 5 run on the JVM and gave up because there was just too much effort involved in maintaining compatibility and too much of it couldn't be properly compiled because of the dynamism of perl and balancing when to interpret and when to compile was becoming a pain.

In any case, losing XS throws so much of CPAN out...

James

**Comment by yuki-kimoto** [comment]
stevan, thanks.
It is best to do what you want to do and are interested in!
Don't care my words.
